package co.com.nutresa.nautiluslogger.middlewareclient;

import java.util.Date;

public class TopicOffset {

  private static final long serialVersionUID = -7221053120581413556L;
  

  /** nombre del topic */
  protected String topicName;

  /** fecha en que se actualiz� por �ltima vez este objeto */
  protected Date lastUpdated;

  /** offset del �ltimo mensaje leido de este topic en el middleware */
  protected long offset;
  /**
  * Default Constructor
  */
  public TopicOffset () {
    super();
  }
  /**
   * Constructor with mandatory attributes
   */  
  public TopicOffset (String topicName, long offset) {
   	super();
    this.setTopicName(topicName);
    this.setOffset(offset);
    
  }
  

  /**
   * Get nombre del topic 
   * @return topicName
   */
  public String getTopicName() {
    return topicName;
  }

  /** 
   * Set nombre del topic
   * @param topicName
   */
  public TopicOffset setTopicName(String topicName) {
    this.topicName = topicName;
    return this;
  }
	
  /**
   * Get fecha en que se actualiz� por �ltima vez este objeto 
   * @return lastUpdated
   */
  public Date getLastUpdated() {
    return lastUpdated;
  }

  /** 
   * Set fecha en que se actualiz� por �ltima vez este objeto
   * @param lastUpdated
   */
  public TopicOffset setLastUpdated(Date lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }
	
  /**
   * Get offset del �ltimo mensaje leido de este topic en el middleware 
   * @return offset
   */
  public long getOffset() {
    return offset;
  }

  /** 
   * Set offset del �ltimo mensaje leido de este topic en el middleware
   * @param offset
   */
  public TopicOffset setOffset(long offset) {
    this.offset = offset;
    return this;
  }
	


// AUTOGENERATED CODE - DO NOT MODIFY 

// Write your own code under this line.

}
